export const TEAM: Record<string, { code: string; flag: string }> = {
  Mexico:                   { code: "MEX", flag: "/flags/Mexico.svg" },
  "South Africa":           { code: "RSA", flag: "/flags/South_Africa.svg" },
  "South Korea":            { code: "KOR", flag: "/flags/South_Korea.svg" },
  Czechia:                  { code: "CZE", flag: "/flags/Czechia.svg" },
  Canada:                   { code: "CAN", flag: "/flags/Canada.svg" },
  "Bosnia and Herzegovina": { code: "BIH", flag: "/flags/Bosnia_and_Herzegovina.svg" },
  USA:                      { code: "USA", flag: "/flags/USA.svg" },
  Paraguay:                 { code: "PAR", flag: "/flags/Paraguay.svg" },
  Qatar:                    { code: "QAT", flag: "/flags/Qatar.svg" },
  Switzerland:              { code: "SUI", flag: "/flags/Switzerland.svg" },
  Brazil:                   { code: "BRA", flag: "/flags/Brazil.svg" },
  Morocco:                  { code: "MAR", flag: "/flags/Morocco.svg" },
  Haiti:                    { code: "HAI", flag: "/flags/Haiti.svg" },
  Scotland:                 { code: "SCO", flag: "/flags/Scotland.svg" },
  Australia:                { code: "AUS", flag: "/flags/Australia.svg" },
  "Türkiye":                { code: "TUR", flag: "/flags/Turkiye.svg" },
  Germany:                  { code: "GER", flag: "/flags/Germany.svg" },
  "Curaçao":                { code: "CUR", flag: "/flags/Curacao.svg" },
  Netherlands:              { code: "NED", flag: "/flags/Netherlands.svg" },
  Japan:                    { code: "JPN", flag: "/flags/Japan.svg" },
  "Ivory Coast":            { code: "CIV", flag: "/flags/Ivory_Coast.svg" },
  Ecuador:                  { code: "ECU", flag: "/flags/Ecuador.svg" },
  Tunisia:                  { code: "TUN", flag: "/flags/Tunisia.svg" },
  Sweden:                   { code: "SWE", flag: "/flags/Sweden.svg" },
  Spain:                    { code: "ESP", flag: "/flags/Spain.svg" },
  "Cape Verde":             { code: "CPV", flag: "/flags/Cape_Verde.svg" },
  Belgium:                  { code: "BEL", flag: "/flags/Belgium.svg" },
  Egypt:                    { code: "EGY", flag: "/flags/Egypt.svg" },
  "Saudi Arabia":           { code: "KSA", flag: "/flags/Saudi_Arabia.svg" },
  Uruguay:                  { code: "URU", flag: "/flags/Uruguay.svg" },
  Iran:                     { code: "IRN", flag: "/flags/Iran.svg" },
  "New Zealand":            { code: "NZL", flag: "/flags/New_Zealand.svg" },
  France:                   { code: "FRA", flag: "/flags/France.svg" },
  Senegal:                  { code: "SEN", flag: "/flags/Senegal.svg" },
  Iraq:                     { code: "IRQ", flag: "/flags/Iraq.svg" },
  Norway:                   { code: "NOR", flag: "/flags/Norway.svg" },
  Argentina:                { code: "ARG", flag: "/flags/Argentina.svg" },
  Algeria:                  { code: "ALG", flag: "/flags/Algeria.svg" },
  Austria:                  { code: "AUT", flag: "/flags/Austria.svg" },
  Jordan:                   { code: "JOR", flag: "/flags/Jordan.svg" },
  Portugal:                 { code: "POR", flag: "/flags/Portugal.svg" },
  "Congo DR":               { code: "COD", flag: "/flags/Congo_DR.svg" },
  England:                  { code: "ENG", flag: "/flags/England.svg" },
  Croatia:                  { code: "CRO", flag: "/flags/Croatia.svg" },
  Ghana:                    { code: "GHA", flag: "/flags/Ghana.svg" },
  Panama:                   { code: "PAN", flag: "/flags/Panama.svg" },
  Uzbekistan:               { code: "UZB", flag: "/flags/Uzbekistan.svg" },
  Colombia:                 { code: "COL", flag: "/flags/Colombia.svg" },
};

export function teamData(name: string) {
  return TEAM[name] ?? { code: name.slice(0, 3).toUpperCase(), flag: "" };
}
